# -*- coding: utf-8 -*-
"""add.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XA654fdek46Qa3GUv06hr44gr1wz2n6Z
"""

a = 1
b = 2
print (a+b)

